name: Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16' # Or your preferred Node.js version
    - run: npm install
    - run: npm run build
    - uses: actions/setup-node@v3
      with:
        node-version: '16' # Or your preferred Node.js version
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
      with:
        service-account-file: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        project-id: buuksao
    - run: gcloud --quiet components install firebase
    - run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
